name: Build docker image
on: 
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v2 # Checking out the repo
      with:
        submodules: true

    - name: Build and Publish latest Docker image
      uses: fl4shback/gp-docker-action@v1.2.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: fl4shback/twitch-rec # Provide only Docker image name, tag will be automatically set to latest
        dockerfile: Dockerfile
